import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import java.io.FileWriter

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.1.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "2.0.0"
    id ("org.jetbrains.kotlin.plugin.serialization") version "2.0.0"

    // For my fat JAR needs
    id("com.github.johnrengelman.shadow") version "8.1.1"

    // Apply the test-logger plugin to add support outputting test results neatly.
    id("com.adarshr.test-logger") version "4.0.0"

    // Apply the org.jetbrains.dokka plugin to generate documentation.
    id("org.jetbrains.dokka") version "1.9.20"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    jacoco
}

group = "kjm.fit.converter"
version = "0.4.12-alpha"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("com.garmin:fit:21.171.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.7.0")

    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.3")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.10.3")
}

val jvmTargetMajorVersion = 21

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(jvmTargetMajorVersion))
    }
}

tasks.withType<KotlinCompile>() {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_21)
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenLocal") {
            groupId = "${group}"
            artifactId = "kotlin-fit-converter-lib"
            version = "${project.version}"

            from(components["java"])
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/" + System.getenv("GITHUB_ACTOR") + "/kotlin-fit-converter")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("PACKAGE_TOKEN")
            }
        }
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    jacoco {
        enabled = true
    }
}

tasks {
    shadowJar {
        archiveClassifier.set("")
    }
}

tasks.dokkaHtml {
    outputDirectory.set(buildDir.resolve("documentation/html"))
}

tasks.register("copyDokkaDocs") {
    dependsOn("dokkaHtml")
    doLast {
        val dokkaDocsDir = file("${buildDir}/documentation/html")
        val targetDocsDir = file("../docs")

        if (dokkaDocsDir.exists()) {
            targetDocsDir.deleteRecursively()
            targetDocsDir.mkdirs()
            dokkaDocsDir.copyRecursively(targetDocsDir)
        } else {
            logger.warn("Dokka documentation directory not found. Please ensure Dokka has been executed.")
        }
    }
}

tasks.register("bumpVersionAndUpdateReadme") {
    group = "versioning"
    description = "Bumps the version and updates the README file"

    doLast {
        // Split the current version string into components
        val versionParts = version.toString().split("-")
        val versionComponents = versionParts[0].split(".").map { it.toInt() }.toMutableList()
        val preRelease = if (versionParts.size > 1) "-${versionParts[1]}" else ""

        // Increment the patch version
        versionComponents[2]++

        // Construct the new version string
        val newVersionString = "${versionComponents.joinToString(".")}$preRelease"

        // Update the version in the build.gradle.kts file
        val buildFile = File("kotlin-fit-converter-lib/build.gradle.kts")
        val buildFileLines = buildFile.readLines()
        val updatedBuildFileLines = buildFileLines.map { line ->
            if (line.startsWith("version =")) {
                "version = \"$newVersionString\""
            } else {
                line
            }
        }

        FileWriter(buildFile).use { writer ->
            updatedBuildFileLines.forEach { writer.write("$it\n") }
        }

        // Update the version badge in the README file
        val readmeFile = File("README.md")
        val readmeFileLines = readmeFile.readLines()
        val updatedReadmeFileLines = readmeFileLines.map { line ->
            if (line.contains("[![Latest Release]")) {
                val newBadge = "[![Latest Release](https://img.shields.io/badge/$newVersionString-red)](https://github.com/example/garmin-fit-converter/releases)"
                newBadge
            } else {
                line
            }
        }

        FileWriter(readmeFile).use { writer ->
            updatedReadmeFileLines.forEach { writer.write("$it\n") }
        }

        println("Version bumped to $newVersionString and README file updated")
    }
}
